apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfocomponent-version
  namespace: ocm-system
spec:
  component: ocm.software/podinfo
  interval: 10m0s
  repository:
    url: ghcr.io/open-component-model/podinfo
  version:
    semver: 1.0.0
