apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfocomponent-version
  namespace: ocm-system
spec:
  component: ocm.software/podinfo
  interval: 10m0s
  references:
    expand: true
  repository:
    url: ghcr.io/open-component-model/mpas-demo-component
  serviceAccountName: admin-account
  version:
    semver: 1.0.16
