apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: Resource
    name: podinfo-resource
  path: "./podinfo"
  prune: true
  timeout: 1m