apiVersion: delivery.ocm.software/v1alpha1
kind: LocalizationConfig
metadata:
  name: deployment-localization
spec:
  rules:
  - source:
      resource:
        name: image
    target:
      file:
        path: podinfo/deployment.yaml
        value: spec.template.spec.containers[0].image
    transformation:
      type: Repository