apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  labels:
  name: resource-localization-instruction
spec:
  componentRef:
    name: podinfo-component
  interval: 10m
  resource:
    byReference:
      resource:
        name: manifests-localization