apiVersion: delivery.ocm.software/v1alpha1
kind: ResourceConfig
metadata:
  name: podinfo-config
spec:
  rules:
  - yamlsubst:
      source:
        value: 2
      target:
        file:
          path: podinfo/deployment.yaml
          value: spec.replicas
