apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-helm
  namespace: default
spec:
  interval: 30s
  chartRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: LocalizedResource
    name: localized-manifest-resource
    namespace: default