apiVersion: delivery.ocm.software/v1alpha1
kind: LocalizationConfig
metadata:
  name: deployment-localization
spec:
  rules:
  - source:
      resource:
        name: image
    target:
      file:
        path: values.yaml
        value: image.repository
    transformation:
      type: Repository